### DISCUSSION TITLE
Updated Transaction Model

### DISCUSSION THREAD

**Discussion by wjones127** [lance-format/lance#3734] [Lance Table Format]
## TLDR

Introduce `CompositeOperation` to allow a `Transaction` with multiple operations in one.

The new operation type could also be an opportunity to solve several other long-standing issues with transactions.

## Design goals

**Primary goal: Allow merging multiple transactions into one.**

Part of merging will need to be conflict resolution. To make this possible, transactions need to serve as true diffs between manifests. In some respects already they do: an Append operation shows the new fragments added. But other operations are not helpful: in `Update` operation, we just provide the new fragments, but it's unclear which data files were modified. If we want to detect conflicts thoroughly, we need to be able to tell from just the transaction what changed.

Secondary goals we can accomplish while refactoring transactions:
* Provide a user-friendly view of dataset operation history (something like [DESCRIBE HISTORY](https://docs.databricks.com/aws/en/sql/language-manual/delta-describe-history) from Delta Lake or `history` metadata table from Iceberg)
* Allow formulating new transaction types **without** having to create new protobuf messages and new conflict resolution implementations.

## Use cases

If `Transaction` can be merged, this unlocks three different use cases:

### Use case 1: Higher write TPS

Currently, each transaction requires committing a new manifest to storage. This makes the sequential writing of this file a bottleneck. If you can merge transactions, then you could batch many operations, and commit several at once.

<img width="940" alt="Screenshot 2025-04-23 at 4 33 58 PM" src="https://github.com/user-attachments/assets/fe9dd1fb-1a53-44bc-bad1-219419102a91" />

### Use case 2: Simplified distributed commits

Right now, when users do distributed writes, they have to construct transactions themselves. This means handling the `read_version` and `blob_operation` themselves, which can sometimes be confusing. If instead we made each partial change return a transaction, we could merge these transactions later before committing the overall operation.

<img width="919" alt="Screenshot 2025-04-23 at 4 35 14 PM" src="https://github.com/user-attachments/assets/49f454c6-75aa-48e8-8a1c-a82b6cf67e54" />

<img width="907" alt="Screenshot 2025-04-23 at 4 35 26 PM" src="https://github.com/user-attachments/assets/ded4c8dc-ab4a-4e06-be06-f3209cbbce1e" />

This is already implemented for append, where you can use [InsertBuilder::execute_uncommitted()](https://docs.rs/lance/latest/lance/dataset/struct.InsertBuilder.html#method.execute_uncommitted) to write new data files, and it returns a `Transaction`. Meanwhile [CommitBuilder::execute_batch()](https://docs.rs/lance/latest/lance/dataset/struct.CommitBuilder.html#method.execute_batch) can take an array of `Transaction`.

### Use case 3: Multi-statement transactions

Combining successive transactions could also be used to do multi-statement transactions. To make successive operations see the one before, this would have to be combined with detached commits. We could make several detached commits, then take the transaction files from those commits, merge them, and use that to commit the multi-statement transaction.

<img width="915" alt="Screenshot 2025-04-23 at 4 39 30 PM" src="https://github.com/user-attachments/assets/3c671d97-48b7-48a5-97ac-602efd58142b" />

## Proposed design

An early prototype exists here: https://github.com/lancedb/lance/pull/3204

Provide a new `CompositeOperation` type that is meant to be a generic operation type. It will be three levels:

* `CompositeOperation` represents the full operation that is applied to create the next version of the manifest
* Has multiple `UserOperation`, which represent a logical user-facing operation. (For example, delete multiple rows.)
* Each `UserOperation` contains multiple `Actions`, which represent a single change to the manifest.

To apply a `CompositeOperation` to create a new manifest, simply apply the flattened list of `Action`s in order.

<details><summary>Example</summary>
<p>

Consider the SQL query:

```sql
BEGIN TRANSACTION;
INSERT INTO t VALUES (1);
DELETE FROM t WHERE id = 32;
UPDATE t SET a = 2 WHERE id = 1;
COMMIT;
```

Could be represented as a single `CompositeOperation`:

```yaml
- description: "INSERT INTO t VALUES (1);"
  uuid: 123e4567-e89b-12d3-a456-426655440001
  read_version: 0
  actions:
    - type: add_fragments
      fragments:
        - id: 10
          files:
            - path: data/123e4567-e89b-12d3-a456-426655440000.lance
              fields: [0]
- description: "DELETE FROM t WHERE id = 32;"
  uuid: 123e4567-e89b-12d3-a456-426655440002
  read_version: 0
  actions:
    - type: updated_fragments
      fragments:
        - id: 0
          files:
            - path: data/dfdsfdsd-e89b-12d3-a456-426655440000.lance
              fields: [0]
              deletion_file:
                - file_type: ARROW_ARRAY
                  read_version: 0
                  id: 10
                  num_deleted_rows: 1
- description: "UPDATE t SET a = 2 WHERE id = 1;"
  uuid: 123e4567-e89b-12d3-a456-426655440003
  read_version: 0
  actions:
    - type: updated_fragments
      fragments:
        - id: 0
          files:
            - path: data/123e4567-sdfs-12d3-sdfs-426655440000.lance
              fields: [0]
              deletion_file:
                - file_type: ARROW_ARRAY
                  read_version: 0
                  id: 10
                  num_deleted_rows: 1
```

</p>
</details> 

https://github.com/lancedb/lance/blob/5ea6589286ef3dd66174b0296f880934e01a1470/protos/transaction.proto#L93-L124
